### PR TITLE
Implement Adjustments for CLEF

### PR DESCRIPTION
**Pull request by ieggel**
Implemented the following:
- Organizer edit page => Can choose if CLEF organizer
- ( Note: If challenge is created by CLEF organizer, clef_challenge field in challenge table is set to true)
- db/seeds/clef/clef.rb  in order to get started quickly with CLEF related stuff (I ran: rails runner -e development db/seeds/clef/clef.rb)
- Possibility to show/create/edit tasks on organizer page (Tasks tab), only active if CLEF organizer 
- (Note: A task is an umbrella for CLEF challenges that share the same dataset)
- (Note: dataset files are added to the table task_dataset_files)
- On the show task page, dataset files can be added
==> PROBLEM: there seems a problem with adding dataset files, the dataset_file_s3_key does not seem to be added to the db
- (Note: End User Agreement (EUA) PDF template can be uploaded when creating task. If this file is present for a task, this means that before being able to access the datasaset, the participant must upload a signed EUA (EUA required))
- (Note: If 2 challenges belong to the same task (with EUA required),  the participant does not need to provide 2 different EUAs. Instead the permission is granted on a per task basis, not challenge basis)
- Possibility to assign CLEF task to a challenge => Challenge edit > Submissions > CLEF task (dropdown)
- (Note: As soon as a challenge is assigned to a task, the resource page (resource tab) is handled by the CLEF workflow in order to get access to a dataset)
- Integrated CLEF workflow into resources page (resources tab)
- (Note: CLEF workflow to get access to a dataset:
    1. In any case: Participant has to provide some specific info on his profile page, such as first name, 
        last name, affiliation, etc.)
    2.1 EUA required: If EUA is required, participant has to upload EUA. As soon as EUA is accepted by an organizer (notified by e-mail) on the participants tab page, the participant can access the dataset.
    2.2 EUA NOT required: If no EUA is required, the participant simply has to agree that the data will be shared with CLEF.)
==> PROBLEM: EUA cannot be downloaded, the link does not work (404). I have no idea why.
- Integrated EUA approval on participants page (participants tab)
==> PROBLEM: EUA that user uploaded cannot be opened (404)

@nemaniarjun please have a look. As soon as i know how to solve the issues, i will continue to work on the rest.

### CODE REVIEW

**Comment by nemaniarjun** [comment]
Hey @ieggel, 
I have started working on this branch and making progress with changing views and making my way through the workflow.

The issue with uploading and downloading files seems to be due to misconfiguration in the development environment relating to fog and localstack, which I am try to sort out properly.

Let me know when you are back in office, we can discuss the progress in detail over a call.

**Comment by nemaniarjun** [comment]
The EUAs downloading has been fixed. 

@ieggel Are task dataset files small enough to upload to s3? should we add the option to directly just take in an external url instead of uploading it to s3 from the rails app? That would make more sense and we can even move it to wasabi later @spMohanty

It should be straight-forward, we would just need to change the db to take in a url instead of an s3 key.

**Comment by ieggel** [comment]
@nemaniarjun 
I would prefer to keep the structure for now. The goal right now is to have the CLEF integration ready ASAP with the same features we had before, also in order not to confuse the CLEF organizers. Also for the challenge migrations this will be easier.

**Comment by nemaniarjun** [comment]
In that case, I would vote to let the code be the same as it is now. We should test the aws integration on production. We should deploy this somewhere, attach it to a s3 and test out the code. The problems that we are facing are due to errors in devleopment environment.

**Comment by nemaniarjun** [comment]
The best would be to mimic what we are doing with dataset files (non clef) having the option for both upload to s3 and external url.

**Comment by spMohanty** [comment]
Thanks @nemaniarjun and @ieggel for seeing this through !! If there are any major blockers which will take an excessive amount of time, please do keep me in the loop.

**Comment by ieggel** [comment]
@nemaniarjun 
OK with the external URL. But before doing let's get everything up and running first. We can then add it after.

**Comment by ieggel** [comment]
@nemaniarjun 
There is still a problem with uploading dataset files, as described in my PR above:
On the show task page, dataset files can be added
==> PROBLEM: there seems a problem with adding dataset files, the dataset_file_s3_key does not seem to be added to the db

In order to add task_dataset_files, go to the organizer page, then tasks, then select a task (create one before) and then select 'add dataset file'. If you go back to the task detail page you will see an error. This error happens because the db field for the dataset_file_s3_key is empty.
Thanks for your help.

**Comment by nemaniarjun** [comment]
Yes, thus instead of uploading it to s3, I suggest we link the dataset
files using external url. This should be fixed, but that will take time.

For datasets for normal non clef challenges, this is working on production
but not on local development env.

When we are discussing this, remember these are issues with the local
development environment, when we actually use AWS this should not be the
case, if you can, create an s3 bucket, set rails ENV vars accordingly,
evaluated in initializes/aws.rb and try to see if the upload works.

If it doesn't work, we will copy the functionality from (dataset files) non
clef  to (task data set file) clef.


We can schedule a call tomorrow to go over the code together and create a
plan of action for the migration.

Does that work for you?

**Comment by ieggel** [comment]
Sounds good @nemaniarjun 
Can we have a call on Thursday rather than tomorrow? As you live in Hyderabad I just had a look at your timezone and it seems you are 4h30min ahead of Switzerland, which right now is in the CEST timezone (UTC +2).
We can have a skype call around 9AM my time, which translates to 1:30pm your time. OK for you?
In the meantime i'll try to fix the remaining things and see if there are any other issues.

**Comment by nemaniarjun** [comment]
Sure that works.

I'll email you the call details for that time.

**Comment by ieggel** [comment]
@nemaniarjun 
Added the additional code to the branch.
Everything that I could think of at the moment should work.
Regarding task_dataset_files: I did not test that, because it did not work locally with localstack. As you've already said, this should work in prod.
Another thing: I reverted the code in app/controllers/api/submission_controller.rb to the version implemented in crowdai. I kept your code commented. Back at the the time I created this API together with Sean so i could easily get back all submissions metadata for a challenge. I heavily use this API, so could we please leave it as it was before? If this is not possible could you make this very my API available under a different name (url) and keep yours at the same time?

**Comment by ieggel** [comment]
@nemaniarjun 
@spMohanty 
When will this be revised and merged?
Thanks

**Comment by spMohanty** [comment]
Nudge 👼 !! Looking for the resolution of this thread soon :)

**Comment by nemaniarjun** [comment]
The branch is active on aicrowd-redesign.herokuapp.com please check if all the features are working as expected @ieggel. 
 @mridulnagpal if you have the time, please check the general non-clef pages as well.

**Comment by ieggel** [comment]
I went to aicrowd-redesign. I created an organizer and multiple organizer accounts linked to that organizer, however i cannot confirm the accounts via the admin-interface (active admin). I think it is best if i remove the users and you execute my custom seed script in order to put some clef specific records into the staging DB. Can you please run the script _**db/seeds/clef.rb**_ ASAP?

**Comment by ieggel** [comment]
So instead of creating new users linked to an organizer i used some existing ones and assiged them to an organizer in the admin interface. This of course works but i don't know if that's how you want things.
I will check things out now and report back.

**Comment by nemaniarjun** [comment]
@ieggel sure, let's schedule a call for when we have identified the issues.

**Comment by ieggel** [comment]
There is a problem with the submission page.
To reproduce:
- Login with user p5593
- go to challenges/imageclef-2019-tuberculosis-severity-scoring
- Hit **_Create Submission_** button
- It will produce a 500 error

This has worked so far for me locally. Can you have a look at the server logs?

**Comment by nemaniarjun** [comment]
The round was not marked as the current_round for some reason. This should be a separate issue (unrelated to clef), I have marked it as current_round for now and the submission page opens now.

**Comment by ieggel** [comment]
Thanks @nemaniarjun 
Another issue: It seems that everything related to S3 does not work. Is this on intention? I cannot test all features if S3 is disabled.

**Comment by ieggel** [comment]
@nemaniarjun 

To give a bit more detail:
- **Adding dataset** files does not work
  - Error message: "Upload failed"
- **Browser submission** (you call it _online submissions_) do not work
  - Error message: "Upload failed"
- Everything concerning the **EUA workflow works**, also the **upload of EUAs**

**Comment by nemaniarjun** [comment]
@ieggel Please ignore that issue for now. 
I will look into it, mostly its due to a config mismatch in our s3. 

If there are no other issues, we should merge this. I expect it to start working from aicrowd.com

**Comment by ieggel** [comment]
@nemaniarjun 
You have a much broader knowledge of the system than me, so if you think we should merge to master, go ahead. I could not identify any other issues at the moment.
___
After the merge, would it be possible to import the following organizers from crowdai:
- **ImageCLEF**
- **LifeCLEF**

Also, it would be good if you could import the following users (participants) from crowdai:
- ivan.eggel@hevs.ch
  - Link to `ImageCLEF` organizer
- ivan.eggel@gmail.com
  - Link to `LifeCLEF` organizer

**Note**: _If possible, keep the same participant/organizer IDs as in the crowdai DB, i think this would make things easier for the upcoming migration of old challenges/users._

After that i would be able to create ImageCLEF/LifeCLEF 2020 challenges and test things out to see if everything is working regarding S3.

It does not not have to be done today, since I'm too busy right now to test things out. However it would be nice to have it done until Monday, if possible.

Thanks.

**Comment by nemaniarjun** [comment]
@ieggel I will merge this, though we need @mridulnagpal @bkDJ to look at where/how this fits into the migration plans already in place. 
I dont think it will be possible to keep the ids same, but we have a migration plan which should take care of that.

**Comment by ieggel** [comment]
@nemaniarjun 
OK, in that case do not worry about the IDs. I'm waiting for the merge and Organizer record inserts as well as the 2 user accounts inserts, so i can test the CLEF workflow in production.

**Comment by ieggel** [comment]
@nemaniarjun , @spMohanty 
Left you a comment for the routes.rb. Can you please fix it?

After the fixes, would you then merge ASAP? I will also have to test in prod, since the S3 stuff is not working locally nor on staging. As commented before i would need you to:

Import the following organizers from crowdai:
- **ImageCLEF**
- **LifeCLEF**

Import the following users (participants) from crowdai:
- ivan.eggel@hevs.ch
  - Link to `ImageCLEF` organizer
- ivan.eggel@gmail.com
  - Link to `LifeCLEF` organizer

We would soon like to start the new 2020 challenges. We will also have to do the migration. This has been pending since July and time is really slowly running out.

**Comment by nemaniarjun** [comment]
@ieggel 

"The path I set it to is HOST/api/old_submissions/challenge_id for the show and HOST/api/old_submissions?challenge_id=ID for the index. I think that should be alright, let me know if this needs changing. The functionality of the API is not changed."

We can merge once this is resolved!

**Comment by ieggel** [comment]
@nemaniarjun 

Thanks for the clarification. I tested it and i get an empty json array, which is alright, since there have not been any submissions on the staging env.

**This is now ready to merge from my side.**

After the merge, please do not forget to create the organizers/participants that i asked for, so i will be able to test.

Thank you!

**Pull request merged**
