### PR TITLE
Travis: Add code coverage with CodeClimate

### PR DESCRIPTION
**Pull request by nemaniarjun**
Based On: https://docs.codeclimate.com/docs/travis-ci-test-coverage

### CODE REVIEW

**Comment by nemaniarjun** [comment]
https://github.com/codeclimate/codeclimate-rubocop/issues/199

Looks like we need to use some other way to run rubocop as it doesn't support configuration gems (like the one we are using)

**Comment by piotrekpasciak** [comment]
@nemaniarjun 
I'll investigate that issue.

**Comment by piotrekpasciak** [comment]
@nemaniarjun Looks like you've resolved the issue, good job 👍

**Comment by nemaniarjun** [comment]
No @piotrekpasciak I am still trying to get it to run properly. this is much tougher than expected. Github Actions are more complex than I expected.

**Pull request merged**
