### PR TITLE
example using local-time

### PR DESCRIPTION
**Pull request by natejenkins**
@mridulnagpal : Here is a working demo with local-time in a cell.

### CODE REVIEW

**Comment by mridulnagpal** [comment]
@natejenkins Awesome thanks!!

**Comment by mridulnagpal** [comment]
@natejenkins If this is good should I remove the duplicate line and merge?

**Comment by mridulnagpal** [comment]
@natejenkins Some issue with setup for build failing, can you restart the build?

**Comment by spMohanty** [comment]
@natejenkins @mridulnagpal : Were these non deterministic build failures not resolved earlier ?

**Comment by mridulnagpal** [comment]
Add timezone used as well

**Comment by mridulnagpal** [comment]
@natejenkins Rebased it on master, and already changed all UTC times

**Pull request merged**
