### PR TITLE
Fixing tests and Travis (FINALLY!!)

### PR DESCRIPTION
**Pull request by nemaniarjun**

### CODE REVIEW

**Comment by spMohanty** [comment]
@nemaniarjun : Too many force pushes here ! Might make sense to start off in a fresh branch off the master

**Comment by nemaniarjun** [comment]
I am not sure? Force pushes won't make a difference on the history of the
branch.

**Comment by spMohanty** [comment]
Ahh you are right. The branch hasnt (ocassionally) rebased in changes from the master. So should ideally be fine !

**Comment by spMohanty** [comment]
The failing test : 
```
  1) Api::SubmissionsController with valid API key with organiser auth key should respond with numeric status code 200
     Failure/Error: it { expect(response).to have_http_status(200) }
       expected the response to have status code 200 but it was 401
     # ./spec/requests/api/submissions_controller_spec.rb:32:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:109:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:108:in `block (2 levels) in <top (required)>'
```

is not relevant anymore, and can be removed !

**Pull request merged**
